apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: linuxptp-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linuxptp-daemon
subjects:
- kind: ServiceAccount
  name: linuxptp-daemon
  namespace: openshift-ptp
